"""
Dr. Eezy backend API — FastAPI application.

Run with:
    cd backend && source .venv/bin/activate
    uvicorn app.main:app --reload --port 8000

Interactive API docs (auto-generated by FastAPI) will be at:
    http://localhost:8000/docs
"""
import json
import os
from datetime import date

from fastapi import FastAPI, File, HTTPException, Query, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse

from app import config
from app.cv.matcher import match_jobs
from app.cv.parser import parse_cv
from app.models.schemas import (ChatAction, ChatRequest, ChatResponse,
                                 CVUploadResponse, RosterGenerateRequest)
from app.rag.chatbot import answer as chatbot_answer
from app.rag.intent import extract_roster_params, wants_roster
from app.roster.generator import generate_roster
from app.roster.pdf_export import export_roster_to_pdf

app = FastAPI(title="Dr. Eezy API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=config.CORS_ALLOW_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
def health():
    return {"status": "ok", "service": "dr-eezy-api"}


@app.get("/jobs")
def list_jobs():
    with open(config.JOBS_PATH) as f:
        return json.load(f)


@app.get("/staff")
def list_staff():
    with open(config.STAFF_PATH) as f:
        return json.load(f)


@app.post("/chat", response_model=ChatResponse)
def chat(req: ChatRequest):
    if not req.message or not req.message.strip():
        raise HTTPException(status_code=400, detail="message must not be empty")

    # Roster generation is handled as a special case: it's an action, not a
    # question, so we short-circuit the RAG/LLM pipeline entirely and call
    # the roster generator directly. Kept rule-based (see app/rag/intent.py)
    # for the same reason the CV parser is rule-based: fast, deterministic,
    # explainable live, and it never needs the LLM to be running at all.
    if wants_roster(req.message):
        params = extract_roster_params(req.message)
        url = (f"/roster/pdf?start_date={params['start_date'].isoformat()}"
               f"&num_days={params['num_days']}")
        answer_text = (
            f"Sure — I've put together a {params['num_days']}-day staff roster starting "
            f"{params['start_date'].isoformat()}, balanced fairly across each job title and "
            f"respecting shift policy (max 3 consecutive nights, mandatory rest after a night "
            f"shift, doctors and nurses scheduled separately). Click below to download it."
        )
        return ChatResponse(
            answer=answer_text,
            used_local_llm=False,
            sources=[],
            action=ChatAction(type="roster_pdf", url=url, label="📄 Download roster PDF"),
        )

    result = chatbot_answer(req.message, profession=req.profession)
    return result


@app.post("/cv/upload", response_model=CVUploadResponse)
async def upload_cv(file: UploadFile = File(...)):
    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF CVs are supported in this demo")

    file_bytes = await file.read()
    parsed = parse_cv(file_bytes)

    if not parsed.profession:
        raise HTTPException(
            status_code=422,
            detail="Could not determine whether this CV belongs to a Doctor or a Nurse. "
                   "Please make sure the job title appears clearly in the CV.",
        )

    matches = match_jobs(parsed, k=5)

    return CVUploadResponse(
        candidate_name=parsed.candidate_name,
        profession=parsed.profession,
        job_title=parsed.job_title,
        experience_years=parsed.experience_years,
        skills=parsed.skills,
        registration=parsed.registration,
        matches=matches,
    )


@app.post("/roster/generate")
def roster_generate(req: RosterGenerateRequest):
    with open(config.STAFF_PATH) as f:
        staff = json.load(f)
    return generate_roster(staff, start_date=req.start_date, num_days=req.num_days)


@app.post("/roster/pdf")
def roster_pdf(req: RosterGenerateRequest):
    return _build_roster_pdf(req.start_date, req.num_days)


@app.get("/roster/pdf")
def roster_pdf_get(start_date: date = Query(...), num_days: int = Query(7)):
    """Same as the POST version, but as a plain link-friendly GET — this is
    what lets Dr. Eezy hand back a clickable download link from the chat."""
    return _build_roster_pdf(start_date, num_days)


def _build_roster_pdf(start_date: date, num_days: int):
    with open(config.STAFF_PATH) as f:
        staff = json.load(f)

    roster = generate_roster(staff, start_date=start_date, num_days=num_days)
    end_date_str = date.fromordinal(start_date.toordinal() + num_days - 1).isoformat()
    title = f"Medics Online — Staff Roster ({start_date.isoformat()} to {end_date_str})"

    out_path = os.path.join(config.GENERATED_DIR, "roster.pdf")
    export_roster_to_pdf(roster, out_path, title=title)

    return FileResponse(out_path, media_type="application/pdf", filename="medics_online_roster.pdf")